# enable colors in prompt
set -g default-terminal "xterm-256color"

# turn off automatic window renaming
# this allows you to name windows what you want using the , key
set-option -g allow-rename off

