#######################################################
# Variables
#######################################################
export GIT_DIRECTORY=$HOME/git
DOTFILES=$GIT_DIRECTORY/dotfiles

#######################################################
# Oh-my-zsh and Powerlevel10k prompt initialization
#######################################################
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load
ZSH_THEME="powerlevel10k/powerlevel10k"

# Disable marking untracked files under VCS as dirty
DISABLE_UNTRACKED_FILES_DIRTY="true"

#######################################################
# Configure ZSH Plugins
#######################################################
plugins=(asdf git tmux uv zsh-syntax-highlighting)

#######################################################
# Source Oh-my-zsh
#######################################################
source $ZSH/oh-my-zsh.sh

#######################################################
# Source custom configs
#######################################################
source $DOTFILES/enable-vim-prompt.sh
source $DOTFILES/git.sh
source $DOTFILES/shell.sh
source $DOTFILES/windows.sh
source $DOTFILES/custom.sh

#######################################################
# Generated by Powerlevel10k to init prompt
#######################################################
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
