add_newline = false

[python]
disabled = true

[package]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[aws]
disabled = true

[directory]
truncate_to_repo = false
truncation_symbol = ".../"

[git_branch]
format = "on [$branch]($style) "

[conda]
symbol = " "
