#!/bin/sh

# This allows ssh X11 forwarding on WSL2
# Also requires that XLaunch is installed and running when connecting via ssh with -XY
export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
export LIBGL_ALWAYS_INDIRECT=1

# Activate, Deactivate, Create conda environments:
alias \
    acon="conda activate" \
    dcon="conda deactivate" \
    ncon="conda create -y -n"

# Vervosity and settings:
alias \
    grab="history | grep" \
    cp="cp -v" \
    mv="mv -v" \
    rm="rm -v" \
    c="clear" \
    ..="cd ../" \
    ../="cd ../../" \
    ..//="cd ../../../" 

# Colorize commands when possible:
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    la="ls -a --color=auto --group-directories-first" \
    lal="ls -al --color=auto --group-directories-first" 

# Ember aliases:
alias \
    depclean="rm -rf node_modules && yarn install" \
    es="ember s -spr false --proxy https://localhost:5001" \
    esc="ember s -spr false --proxy https://localhost:6001"

# Git aliases:
alias \
    g="git"
    ga="git add" \
    gap="git add -p" \
    gf="git fetch" \
    gc="git commit" \
    co="git checkout" \
    gp="git push" \
    gb="git branch" \
    gs="git status" \
    gsh="git stash" \
    gshl="git stash list" \
    gsha="git stash apply" \
    grb="git rebase -i" \
    grbc="git rebase --continue" \
    grba="git rebase --abort" \
    grbm="git rebase main" \
    gcp="git cherry-pick" \
    gd="git diff" \
    gclean="git clean -fd" \
    gcan="git commit --amend --no-edit"

# Git compound commands:
alias gup=$'git pull --rebase && git remote update origin --prune && git fetch -p && for branch in $(git for-each-ref --format \'%(refname) %(upstream:track)\' refs/heads | awk \'$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}\'); do git branch -D $branch; done'
alias gbail="git reset --hard HEAD@{upstream} && git clean -fd"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %Cblue<%an>%Creset' --abbrev-commit --date=relative"

# Git functions:
save() {
    git add .
    git commit -m $1
    git push
}

gnew() {
    git checkout -b $1
    git push --set-upstream origin $1
}
